import type {
  CatalogEntry,
  ServiceCategory,
} from "@/domain/business/serviceCatalog.types";

const BUSINESS_ID = "business-1";

export const serviceCategories: ServiceCategory[] = [
  {
    id: "cat_001",
    code: "balayage",
    businessId: BUSINESS_ID,
    name: "Balayage",
    order: 0,
    active: true,
  },
  {
    id: "cat_002",
    code: "coloration",
    businessId: BUSINESS_ID,
    name: "Coloration",
    order: 1,
    active: true,
  },
  {
    id: "cat_003",
    code: "coupe",
    businessId: BUSINESS_ID,
    name: "Coupe",
    order: 2,
    active: true,
  },
  {
    id: "cat_004",
    code: "soin",
    businessId: BUSINESS_ID,
    name: "Soin",
    order: 3,
    active: true,
  },
  {
    id: "cat_005",
    code: "brushing",
    businessId: BUSINESS_ID,
    name: "Brushing",
    order: 4,
    active: true,
  },
  {
    id: "cat_006",
    code: "coupe-coiffage",
    businessId: BUSINESS_ID,
    name: "Coupe & Coiffage",
    order: 5,
    active: true,
  },
];

export const serviceCatalog: CatalogEntry[] = [
  {
    id: "svc_001",
    code: "balayage",
    businessId: BUSINESS_ID,
    categoryId: "cat_001",
    name: "Balayage",
    type: "TECHNIQUE",
    order: 0,
    active: true,
    options: [
      {
        id: "opt_001",
        code: "variant-1",
        order: 0,
        activeDurationMinutes: 90,
        processingDurationMinutes: 60,
        price: {
          type: "FIXED",
          amount: 45,
        },
      },
      {
        id: "opt_002",
        code: "variant-2",
        order: 1,
        activeDurationMinutes: 105,
        processingDurationMinutes: 60,
        price: {
          type: "FIXED",
          amount: 50,
        },
      },
      {
        id: "opt_003",
        code: "variant-3",
        order: 2,
        activeDurationMinutes: 120,
        processingDurationMinutes: 60,
        price: {
          type: "FIXED",
          amount: 60,
        },
      },
    ],
  },
  {
    id: "svc_002",
    code: "couleur-racines",
    businessId: BUSINESS_ID,
    categoryId: "cat_002",
    name: "Couleur Racines",
    type: "TECHNIQUE",
    order: 0,
    active: true,
    options: [
      {
        id: "opt_004",
        code: "default",
        order: 0,
        activeDurationMinutes: 45,
        processingDurationMinutes: 20,
        price: {
          type: "FIXED",
          amount: 30,
        },
      },
    ],
  },
  {
    id: "svc_003",
    code: "gloss",
    businessId: BUSINESS_ID,
    categoryId: "cat_002",
    name: "Gloss",
    type: "TECHNIQUE",
    order: 1,
    active: true,
    options: [
      {
        id: "opt_005",
        code: "default",
        order: 0,
        activeDurationMinutes: 10,
        processingDurationMinutes: 10,
        price: {
          type: "CUSTOM",
        },
      },
    ],
  },
  {
    id: "svc_004",
    code: "dose-supplementaire",
    businessId: BUSINESS_ID,
    categoryId: "cat_002",
    name: "Dose Supplémentaire",
    type: "TECHNIQUE",
    order: 2,
    active: true,
    options: [
      {
        id: "opt_006",
        code: "default",
        order: 0,
        activeDurationMinutes: 0,
        processingDurationMinutes: 20,
        price: {
          type: "FIXED",
          amount: 15,
        },
      },
    ],
  },
  {
    id: "svc_005",
    code: "coupe-brushing",
    businessId: BUSINESS_ID,
    categoryId: "cat_003",
    name: "Coupe Brushing",
    type: "TECHNIQUE",
    order: 0,
    active: true,
    options: [
      {
        id: "opt_007",
        code: "variant-1",
        order: 0,
        activeDurationMinutes: 50,
        processingDurationMinutes: 0,
        price: {
          type: "FIXED",
          amount: 40,
        },
      },
      {
        id: "opt_008",
        code: "variant-2",
        order: 1,
        activeDurationMinutes: 65,
        processingDurationMinutes: 0,
        price: {
          type: "FIXED",
          amount: 45,
        },
      },
      {
        id: "opt_009",
        code: "variant-3",
        order: 2,
        activeDurationMinutes: 120,
        processingDurationMinutes: 0,
        price: {
          type: "FIXED",
          amount: 55,
        },
      },
    ],
  },
  {
    id: "svc_006",
    code: "soin-classique",
    businessId: BUSINESS_ID,
    categoryId: "cat_004",
    name: "Soin Classique",
    type: "TECHNIQUE",
    order: 0,
    active: true,
    options: [
      {
        id: "opt_010",
        code: "default",
        order: 0,
        activeDurationMinutes: 5,
        processingDurationMinutes: 10,
        price: {
          type: "FIXED",
          amount: 10,
        },
      },
    ],
  },
  {
    id: "svc_007",
    code: "soin-profond",
    businessId: BUSINESS_ID,
    categoryId: "cat_004",
    name: "Soin Profond",
    type: "TECHNIQUE",
    order: 1,
    active: true,
    options: [
      {
        id: "opt_011",
        code: "default",
        order: 0,
        activeDurationMinutes: 5,
        processingDurationMinutes: 10,
        price: {
          type: "FIXED",
          amount: 15,
        },
      },
    ],
  },
  {
    id: "svc_008",
    code: "traitement-sos",
    businessId: BUSINESS_ID,
    categoryId: "cat_004",
    name: "Traitement SOS",
    type: "TECHNIQUE",
    order: 2,
    active: true,
    options: [
      {
        id: "opt_012",
        code: "default",
        order: 0,
        activeDurationMinutes: 5,
        processingDurationMinutes: 10,
        price: {
          type: "FIXED",
          amount: 80,
        },
      },
    ],
  },
  {
    id: "svc_009",
    code: "brushing",
    businessId: BUSINESS_ID,
    categoryId: "cat_005",
    name: "Brushing",
    type: "SERVICE",
    order: 0,
    active: true,
    options: [
      {
        id: "opt_013",
        code: "variant-1",
        order: 0,
        durationMinutes: 30,
        price: {
          type: "FIXED",
          amount: 20,
        },
      },
      {
        id: "opt_014",
        code: "variant-2",
        order: 1,
        durationMinutes: 45,
        price: {
          type: "FIXED",
          amount: 25,
        },
      },
      {
        id: "opt_015",
        code: "variant-3",
        order: 2,
        durationMinutes: 60,
        price: {
          type: "FIXED",
          amount: 35,
        },
      },
    ],
  },
  {
    id: "svc_010",
    code: "coupe-femme-homme",
    businessId: BUSINESS_ID,
    categoryId: "cat_006",
    name: "Coupe Femme / Homme",
    type: "SERVICE",
    order: 0,
    active: true,
    options: [
      {
        id: "opt_016",
        code: "default",
        order: 0,
        durationMinutes: 20,
        price: {
          type: "FIXED",
          amount: 25,
        },
      },
    ],
  },
  {
    id: "svc_011",
    code: "chignon",
    businessId: BUSINESS_ID,
    categoryId: "cat_006",
    name: "Chignon",
    type: "SERVICE",
    order: 1,
    active: true,
    options: [
      {
        id: "opt_017",
        code: "default",
        order: 0,
        durationMinutes: 60,
        price: {
          type: "FIXED",
          amount: 60,
        },
      },
    ],
  },
];
